# Generated by Django 4.2.12 on 2025-03-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=300)),
                ('milk', models.IntegerField(default=200)),
                ('coffee', models.IntegerField(default=100)),
                ('money', models.FloatField(default=0.0)),
            ],
        ),
    ]
